---
- hosts: cisco
  gather_facts: no
  connection: local

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_ssh_user }}"
      password: "{{ ansible_ssh_password }}"
      authorize: true
      auth_pass: "{{ cisco_enable_password }}"

    loopback_if_name: Loopback9
    loopback_if_ipaddr: 9.9.9.9
    erspan_id: 99
    mon_src_session_num: 11
    mon_dst_session_num: 12
    mon_src_if_name: GigabitEthernet3
    mon_src_if_name_short: Gi3
    mon_dst_if_name_short: Gi1
    mon_if_vlan: true

  tasks:
    - name: get config
      ios_command:
        commands:
          - show running-config
        provider: "{{ cli }}"
      register: config

    - name: delete local erspan
      ios_config:
        lines:
          - no monitor session {{ item }}
        provider: "{{ cli }}"
      when: config.stdout[0].find("monitor session {{ item }}") != -1
      with_items:
        - "{{ mon_src_session_num }}"
        - "{{ mon_dst_session_num }}"

    - name: delete monitor vlan if configured
      ios_config:
        parents:
          - interface {{ mon_src_if_name }}
        lines:
          - no plim ethernet vlan filter disable
        provider: "{{ cli }}"
      when: config.stdout[0].find("plim ethernet vlan filter disable") != -1

    - name: delete loopback interface
      ios_config:
        lines:
          - no interface {{ loopback_if_name }}
        provider: "{{ cli }}"
      when: config.stdout[0].find("interface {{ loopback_if_name }}") != -1

